backend/django/config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "documents/", TemplateView.as_view(template_name="pages/documents.html"), name="documents"
    ),
    #path(
    #    "publish/", TemplateView.as_view(template_name="pages/publish.html"), name="publish"
    #),
    #path(
    #    "market/", TemplateView.as_view(template_name="pages/market.html"), name="market"
    #),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("webcard.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("editor/", include("webcard.editor.urls", namespace="editor")),
    path("packages/", include("webcard.packages.urls", namespace="packages")),
    path("api/", include("webcard.stacks.urls", namespace="api")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

backend/django/webcard/editor/urls.py
from django.urls import path
from django.views.generic import TemplateView
from webcard.editor.views import index, play

app_name = "editor"
urlpatterns = [
    path("", view=index, name="index"),
    path("play/<int:stack_id>/", view=play, name="play"),
    path("audio.html", TemplateView.as_view(template_name="editor/audio.html"), name="audio"),
    path("editor.html", TemplateView.as_view(template_name="editor/editor.html"), name="editor"),
    path("script.html", TemplateView.as_view(template_name="editor/script.html"), name="script"), # need work
    path("icon.html", TemplateView.as_view(template_name="editor/icon.html"), name="icon"),
    path("msgbox.html", TemplateView.as_view(template_name="editor/msgbox.html"), name="msgbox"),
]

backend/django/webcard/stacks/urls.py
# coding: utf-8
from django.urls import include, path
from rest_framework import routers
from .views import StackViewSet, AuthorViewSet
from webcard.packages.views import PackageViewSet

router = routers.DefaultRouter()
router.register(r'stacks', StackViewSet)
router.register(r'authors', AuthorViewSet)
router.register(r'packages', PackageViewSet)

app_name = "stack" # humm... now packages are included, need concern.
urlpatterns = [
    path(r'v1/', include(router.urls), name="api-root"),
]

backend/django/webcard/users/urls.py
from django.urls import path

from webcard.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

backend/django/webcard/editor/models.py
from django.db import models

# Create your models here.

backend/django/webcard/stacks/models.py
from django.db import models
# from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.postgres.fields import JSONField
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()

class Stack(models.Model):
    # list of states
    STATUS_DEVELOP = "develop"
    STATUS_TESTING = "staging"
    STATUS_PUBLISH = "publish"
    STATUS_SET = (
        (STATUS_DEVELOP, "Under Development"),
        (STATUS_TESTING, "Under Staging"),
        (STATUS_PUBLISH, "Published"),
    )
    # name of this stack
    title = models.CharField(max_length=128)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="stacks")
    status = models.CharField(choices=STATUS_SET, default=STATUS_DEVELOP, max_length=8)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # Yes! we are using Postgres JSONField! omit encoder=DjangoJSONEncoder
    data = JSONField()

backend/django/webcard/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

backend/django/webcard/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

backend/django/webcard/editor/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from rest_framework.reverse import reverse_lazy
from django.conf import settings

# Create your views here.
User = get_user_model()

def index(request):
    context = {
        'User': request.user,
        'ApiUrl': reverse_lazy('stack:api-root', request=request),
        'settings': settings,
    }
    return render(request, 'editor/index.html', context)

def play(request, stack_id):
    context = {
        'User': request.user,
        'ApiUrl': reverse_lazy('stack:api-root', request=request),
        'StackId': stack_id,
        'settings': settings,
    }
    return render(request, 'editor/index.html', context)

backend/django/webcard/stacks/views.py
# coding: utf-8
#from django.shortcuts import render
#import django_filters
from django.contrib.auth import get_user_model
from rest_framework import viewsets, filters, permissions
from .models import Stack
from .serializers import StackSerializer, StackListSerializer, AuthorSerializer

# Create your views here.
User = get_user_model()

class IsOwnerOrReadOnly(permissions.BasePermission):
    """
    Object level permission to only show owners of an object to edit
    """
    def has_object_permission(self, request, view, obj):
        # Read permissions are allowed to any request,
        # so we'll always allow GET, HEAD, or OPTIONS request
        if request.method in permissions.SAFE_METHODS:
            return True
        # check instance owner is myself
        return obj.author == request.user

class AuthorViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = AuthorSerializer
    filter_fields = ('username',)
    permission_classes = (IsOwnerOrReadOnly,)
    def get_queryset(self):
        # just show me, or otherwise anyone can see other's email!
        queryset = User.objects.filter(username=self.request.user)
        return queryset
    

class StackViewSet(viewsets.ModelViewSet):
    queryset = Stack.objects.all()
    permission_classes = (IsOwnerOrReadOnly,)
    #serializer_class = StackSerializer
    def get_serializer_class(self):
        if self.action == 'list':
            return StackListSerializer
        else:
            return StackSerializer
    filter_fields = ('title', 'author', 'status',)
    def get_queryset(self):
        queryset = Stack.objects.filter(status="publish")
        if (str(self.request.user) != "AnonymousUser"):
            # just show my stacks list or any published stacks
            mystacks = Stack.objects.filter(author=self.request.user)
            queryset = mystacks | queryset
        return queryset

backend/django/webcard/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

backend/django/webcard/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}WebCard{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="m-0 p-0" id="HomeMenuBar">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">WebCard</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active" id="navHome">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item d-none" id="navAbout">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item" id="navDocuments">
              <a class="nav-link" href="{% url 'documents' %}">Documents</a>
            </li>
            <li class="nav-item" id="navEditor">
              <a class="nav-link" href="{% url 'editor:index' %}">Develop</a>
            </li>
            <li class="nav-item" id="navPublish">
              <a class="nav-link" href="{% url 'packages:publish' %}">Publish</a>
            </li>
            <li class="nav-item" id="navMarket">
              <a class="nav-link" href="{% url 'packages:market' %}">Market</a>
            </li>
          </ul>
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ request.user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="dropdown-item" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="dropdown-item" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </div>
              </li>
            </ul>
            {% else %}
              <form class="form-inline ml-auto">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="btn btn-outline-secondary" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="btn btn-primary ml-2" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </form>
            {% endif %}
        </div>
      </nav>

    </div>

    <div class="container p-0 m-0">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 